### PR TITLE
moving copy meta onto context

### PR DESCRIPTION
**Pull request by wheresrhys**

### CODE REVIEW

**Comment by wheresrhys** [comment]
cc @markstephens

**Comment by markstephens** [comment]
sweet! :+1:

**Comment by wheresrhys** [comment]
I'm also gonna stop sending these events to keen so NGDA will be a single source of truth for this now it's on the context object

**Comment by markstephens** [comment]
Oh, why? Reduce load?

**Comment by wheresrhys** [comment]
keen doesn't like really long strings in property values, so we'd have to work around that. We don't use this info for anything anyway at the moment

**Comment by markstephens** [comment]
Neither does Redshift! :)

**Comment by wheresrhys** [comment]
What's redshift's character limit

**Comment by markstephens** [comment]
Roughly 64k bytes, but it gets very inefficient at that size. Keen will be a similar degradation of performance with a larger text size, which is why they'll like to limit you

**Comment by chrisbrownuk** [comment]
65531 single byte characters (65535 bytes (64K -1), where 4 bytes + total
bytes for characters, where each character can be 1 to 4 bytes.)

However we'd never want to store anything this big as it uses up all the
memory.

-- 

*Chris Brown*
TPO Web Analytics
Data Technology
Financial Times, One Southwark Bridge, London SE1 9HL

chris.brown@ft.com | +44 (0)207 873 4701

------------------------------

On 10 March 2016 at 11:13, Rhys Evans <notifications@github.com> wrote:

> What's redshift's character limit
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/n-instrumentation/pull/32#issuecomment-194795117>
> .
>

-- 

------------------------------

*This email was sent by a company owned by Financial Times Group Limited 
("FT Group <http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt>"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law.*

**Pull request merged**
