### PR TITLE
Add number of characters to text copy

### PR DESCRIPTION
**Pull request by markstephens**

### CODE REVIEW

**Comment by commuterjoy** [comment]
+1

**Comment by wheresrhys** [comment]
I'd tidy this up by setting selection and length to `null` if getSelection not supported

**Comment by markstephens** [comment]
> I'd tidy this up by setting selection and length to null if getSelection not supported

I wondered that, but didn't want to mess with what was already there... Can do if you want... If you're summing/averaging these values up, a null is better than a zero.

**Comment by commuterjoy** [comment]
Could add a simple wordCount too - `selection.split(' ').length`

**Comment by markstephens** [comment]
Added word count

**Comment by wheresrhys** [comment]
:+1: this leads me to think what other characteristics of the text we could detect. Is it article body? Is it just a link? Proportion of article copied...

Actually, much of that we could do by cross referencing with CAPI in spoor-enrichment. Either way, the more sophisticated we make this, the easier it'll be to fend off tynt

**Comment by markstephens** [comment]
b2b just need count of characters, which is where this came from originally. Dunno what else tynt is used for, thought it was just b2b..

**Comment by markstephens** [comment]
ok to merge?

**Pull request merged**
